import os
import time

print ('R/')
time.sleep(0.5)
os.system('clear')
print ('Rl')
time.sleep(0.5)
os.system('clear')
print ('RA/')
time.sleep(0.5)
os.system('clear')
print ('RAl)
time.sleep(0.5)
os.system('clear')
print ('RAD/')
time.sleep(0.5)
os.system('clear')
print ('RADl')
time.sleep(0.5)
os.system('clear')
print ('RADI/')
time.sleep(0.5)
os.system('clear')
print ('RADIl')
time.sleep(0.5)
os.system('clear')
print ('RADIT/')
time.sleep(0.5)
os.system('clear')
print ('RADITl')
time.sleep(0.5)
os.system('clear')
print ('RADIT /')
time.sleep(0.5)
os.system('clear')
print ('RADIT H')
time.sleep(0.5)
os.system('clear')
print ('RADIT /')
time.sleep(0.5)
os.system('clear')
print ('RADIT HA|')
time.sleep(0.5)
os.system('clear')
print ('RADIT HA/')
time.sleep(0.5)
os.system('clear')
print ('RADIT HA|')
time.sleep(0.5)
os.system('clear')
print ('RADIT HAC/')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACK|')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACK/')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACK|')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACKI/')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACKING|')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACKING/')
time.sleep(0.5)
os.system('clear')
print ('RADIT HACKING')
time.sleep(0.5)
